# Generated by Django 3.2.6 on 2021-08-10 20:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='number')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='response id')),
                ('response', models.TextField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.question')),
            ],
            options={
                'ordering': ['response_id'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('cand_link', models.URLField(blank=True, null=True)),
                ('cand_long_response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cand_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.question')),
            ],
            options={
                'ordering': ['f_name', 'l_name'],
            },
        ),
    ]
