# Generated by Django 3.2.6 on 2021-08-07 18:15

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='survey/')),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('affiliation', models.CharField(blank=True, choices=[('D', 'Democratic'), ('R', 'Republican'), ('U', 'Unafilliated'), ('L', 'Libertarian'), ('N', 'nonpartisan')], max_length=1, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('cand_website', models.URLField(blank=True, null=True)),
                ('cand_facebook', models.URLField(blank=True, null=True)),
                ('cand_twitter', models.URLField(blank=True, null=True)),
                ('cand_insta', models.URLField(blank=True, null=True)),
                ('camp_finance', models.URLField(blank=True, null=True)),
                ('about_cand', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['f_name', 'l_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='number')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='response id')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='response id')),
                ('response', models.TextField(blank=True, max_length=255, null=True)),
                ('cand_response', ckeditor.fields.RichTextField(blank=True, default='', max_length=1200, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='multi.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.question')),
            ],
            options={
                'ordering': ['response_id', 'candidate'],
            },
        ),
    ]
