# Generated by Django 3.2.6 on 2021-08-07 23:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['response_id']},
        ),
        migrations.RemoveField(
            model_name='response',
            name='cand_response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='response',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cand_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_long_response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cand_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.response')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='multi.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.question')),
            ],
        ),
    ]
